name: "Setup Infrastructure"

on:
  workflow_dispatch:
  push: 
    branches:
      - feature/setup-infra
      - main
    paths:
      - ".github/workflows/setup-infra.yml"

jobs:
  setup_infra:
    runs-on: ubuntu-latest
    env:
      PROXMOX_API_TOKEN_ID: ${{ secrets.PROXMOX_API_TOKEN_ID }}
      PROXMOX_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
      PROXMOX_HOST: ${{ secrets.PROXMOX_HOST }}
      PROXMOX_PVE_USER: ${{ secrets.PROXMOX_PVE_USER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installing WireGuard
        run: |
          sudo apt update
          sudo apt install -y wireguard

      - name: Configure WireGuard
        run: |
          cat <<EOF | sudo tee /etc/wireguard/wg0.conf > /dev/null
          [Interface]
          PrivateKey = ${{ secrets.WG_GA_PRIV_KEY }}
          Address = ${{ secrets.WG_GA_IP }}

          [Peer]
          PublicKey = ${{ secrets.WG_OPNSENSE_PUB_KEY }}
          Endpoint = ${{ secrets.WG_OPNSENSE_ENDPOINT }}
          AllowedIPs = ${{ secrets.WG_GA_ALLOWED_IPS }}
          PersistentKeepalive = 25
          EOF
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Start WireGuard
        run: |
          sudo systemctl start wg-quick@wg0

      - name: Check VPN Connection
        run: |
          echo "Checking VPN connection..."
          ip a show wg0 
          ping -c 4 ${{ secrets.OPNSENSE_LOCAL_IP }}  # Ping OPNsense
          ping -c 4 ${{ secrets.PROXMOX_LOCAL_IP }} # Ping Proxmox

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Generate Terraform Backend Config
        run: |
          cat <<EOF > terraform/backend.hcl
          hostname = "${{ vars.TF_CLOUD_HOSTNAME }}"
          organization = "${{ vars.TF_CLOUD_ORGANIZATION }}"
          workspaces {
            name = "${{ vars.TF_CLOUD_WORKSPACE}}"
          }
          EOF

      - name: Terraform Init
        working-directory: terraform/
        run: |
          terraform init -backend-config=backend.hcl

      - name: Stop WireGuard
        if: success()
        run: sudo systemctl stop wg-quick@wg0