name: "Setup Infrastructure"

on:
  workflow_dispatch:

jobs:
  setup_infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: sudo apt update && sudo apt install -y wireguard

      - name: Configure WireGuard
        run: |
          echo "[Interface]
          PrivateKey = ${{ secrets.WG_GA_PRIV_KEY }}
          Address = ${{ secrets.WG_GA_IP }}
          DNS = 8.8.8.8

          [Peer]
          PublicKey = ${{ secrets.WG_OPNSENSE_PUB_KEY }}
          Endpoint = ${{ secrets.WG_OPNSENSE_ENDPOINT }}
          AllowedIPs = ${{ secrets.WG_GA_ALLOWED_IPS }}
          PersistentKeepalive = 25
          " > wg0.conf
          sudo mv wg0.conf /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Start WireGuard
        run: sudo wg-quick up wg0

      - name: Check VPN Connection
        run: |
          echo "Checking VPN connection..."
          ip a show wg0 
          ping -c 4 ${{ secrets.OPNSENSE_LOCAL_IP }}  # Ping OPNsense
          ping -c 4 ${{ secrets.PROXMOX_LOCAL_IP }} # Ping Proxmox
          sudo wg show
